-->ISOLATION

-->READ UNCOMMITTED DATA
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
SELECT * FROM Person.ContactType

-->READ COMMITTED DATA
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
SELECT * FROM Person.ContactType

-->REPEATABLE READ
BEGIN TRANSACTION
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT Name FROM Person.ContactType WHERE ContactTypeID = 2
SELECT Name FROM Person.ContactType WHERE ContactTypeID = 2
ROLLBACK TRANSACTION

-->SERIALIZABLE
BEGIN TRANSACTION
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT Name FROM Person.ContactType WHERE Name='Agent'
SELECT Name FROM Person.ContactType WHERE Name='Agent'
ROLLBACK TRANSACTION

CREATE DATABASE  Emp
USE Emp
CREATE TABLE Employee
(
EmployeeId INT,
EmployeeName VARCHAR(20)
);
INSERT INTO Employee VALUES(1,'Riya')

-->SNAPSHOT
ALTER DATABASE AdventureWorks2012 SET ALLOW_SNAPSHOT_ISOLATION ON ALTER DATABASE  AdventureWorks2012 SET READ_COMMITTED_SNAPSHOT ON
 
SET TRANSACTION ISOLATION LEVEL SNAPSHOT
SELECT Name FROM Person.ContactType WHERE Name='Owner'
ROLLBACK TRNSACTION

-->DEADLOCK
USE Emp
CREATE TABLE A
(
Name VARCHAR(40) 
)
SELECT * FROM A
INSERT INTO A VALUES('Riya')
DROP TABLE B
DROP TABLE A
CREATE TABLE B
(
Name VARCHAR(40) 
)
SELECT * FROM B
SELECT * FROM A
INSERT INTO B VALUES('Meena')
BEGIN TRANSACTION
UPDATE A SET Name='Neha' WHERE Name='Riya'
BEGIN TRANSACTION
UPDATE B SET Name='Bansari' WHERE Name='Meena'