export interface viewhotelbooking
{
    amount:number,
    tax: number,
    totelAmount: number,
    hotelName:string,
    hotelCity:string,
    hotelState:string,
    hotelAddress:string,
    pinNumber:string,
    rating:string,
    numberOfRoomAvailable:number,
    hotelContectNumber:string,
    hotelEmailAddress:string,
    imgPath1:string,
    imgPath2:string,
    imgPath3:string,
    imgPath4:string,
    userId: number,
    userFirstName: string,
    userMiddleName:string,
    userLastName:string,
    userConformationNumber: string,
    userContactNumber:string,
    userEmailAddress: string,
    numberOfGuest: number,
    bookingDateTime:Date,
    costId:number,
    hotelId:number
}