/*** Day 15 Practice Exercise ***/

-- Implicit Transaction

SET IMPLICIT_TRANSACTIONS ON
INSERT INTO Employees VALUES (8,'G')
INSERT INTO Employees VALUES (9,'H')
COMMIT TRANSACTION;

SET IMPLICIT_TRANSACTIONS OFF

-- Explicit Transaction

BEGIN TRAN myTran
UPDATE Sales
SET Salary = Salary-5000
WHERE Id=1 AND Salary=10000

UPDATE Sales
SET Salary = Salary + 5000
WHERE Id=1 AND Salary=5000
COMMIT TRAN myTran
GO

-- Rollback

BEGIN TRANSACTION myTran
BEGIN TRY
	UPDATE Employees SET Id = 5 WHERE Id = 9
	UPDATE Sales SET Salary = 10000 WHERE Id = 5
	COMMIT TRANSACTION myTran
	SELECT 'Transaction Executed'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION myTran
	SELECT 'Transaction Rollback',ERROR_LINE(),ERROR_MESSAGE()
END CATCH

-- Impliment Isolation Level

-- READ COMMITTED

SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRANSACTION myTran
BEGIN TRY
	UPDATE Employees SET Id = 5 WHERE Id = 9
	UPDATE Sales SET Salary = 10000 WHERE Id = 5
	COMMIT TRANSACTION myTran
	SELECT 'Transaction Executed'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION myTran
	SELECT 'Transaction Rollback',ERROR_LINE(),ERROR_MESSAGE()
END CATCH

-- READ UNCOMMITTED

BEGIN TRANSACTION myTran
	UPDATE Sales SET Salary = 10000 WHERE Id = 3
COMMIT TRANSACTION myTran

	--In new query window
	SET TRANSACTION ISOLATION LEVEL
	READ UNCOMMITTED
	SELECT * FROM Sales WHERE Id=3

-- REPEATABLE
--In new query window
	SET TRANSACTION ISOLATION LEVEL
	REPEATABLE READ
	SELECT * FROM Sales WHERE Id=3

-- SERIALIZABLE
--In new query window
	SET TRANSACTION ISOLATION LEVEL
	SERIALIZABLE
	SELECT * FROM Sales WHERE Id=3

-- SNAPSHOT

ALTER DATABASE SQLTraining SET ALLOW_SNAPSHOT_ISOLATION OFF;
SELECT DB_NAME(database_id) 'Database Name' ,snapshot_isolation_state_desc FROM sys.databases WHERE database_id = DB_ID();
BEGIN TRANSACTION myTran
SET TRANSACTION ISOLATION LEVEL
SNAPSHOT
SELECT * FROM Employees WHERE Id=3
ROLLBACK TRANSACTION myTran

-- In new query window
	UPDATE Sales SET Salary = 10000 WHERE Id = 3
	SELECT * FROM Employees WHERE Id=3

