CREATE DATABASE BookMyShowDB

USE BookMyShowDB

CREATE TABLE Admins(
	AdminId INT CONSTRAINT Admins_AdminId_PK PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	ContactNo CHAR(10) CONSTRAINT Chk_Admins_ContactNo CHECK(ContactNo LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	Password VARCHAR(10) NOT NULL
)

CREATE TABLE Users(
	UserId INT CONSTRAINT Users_UserId_PK PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(50) NOT NULL,
	LastName VARCHAR(50) NOT NULL,
	ContactNo CHAR(10) CONSTRAINT Chk_Users_ContactNo CHECK(ContactNo LIKE '[6-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') NOT NULL,
	Password VARCHAR(10) NOT NULL
)

CREATE TABLE Regions(
	RegionId INT CONSTRAINT Regions_RegionId_PK PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL CONSTRAINT Chk_Regions_Name CHECK(Name IN('North', 'South', 'East', 'West'))
)


CREATE TABLE Cities(
	CityId INT CONSTRAINT Cities_CityId_PK PRIMARY KEY IDENTITY(1,1),
	RegionId INT CONSTRAINT Regions_RegionID_FK FOREIGN KEY REFERENCES Regions(RegionId),
	Name VARCHAR(50) NOT NULL
)

CREATE TABLE Theatres(
	TheatreId INT CONSTRAINT Theatres_TheatreId_PK PRIMARY KEY IDENTITY(1, 1),
	Name VARCHAR(50) NOT NULL,
	CityId INT CONSTRAINT Cities_CityId_FK FOREIGN KEY REFERENCES Cities(CityId) NOT NULL,
	Address VARCHAR(50) NOT NULL
)

CREATE TABLE ShowTimings(
	ShowTimingId INT CONSTRAINT ShowTimings_ShowTimingId_PK PRIMARY KEY IDENTITY(1, 1),
	StartDate DATE NOT NULL,
	EndDate DATE NOT NULL,
	ShowTime TIME NOT NULL
)

CREATE TABLE SeatsCategories(
	SeatsCategoryId INT CONSTRAINT SeatsCategories_SeatsCategoryID_PK PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(50) NOT NULL,
	Price MONEY NOT NULL
)

CREATE TABLE Seats(
	SeatsId INT CONSTRAINT Seats_SeatsId_PK PRIMARY KEY IDENTITY(1,1),
	RowNo CHAR(1) NOT NULL,
	SeatNo INT NOT NULL,
	CONSTRAINT RowNo_SeatNo_UK UNIQUE(RowNo, SeatNo)
)