SELECT  DENSE_RANK() OVER (ORDER BY SALARY DESC) RANK_SALARY , Salary FROM Employees ORDER BY Salary DESC



SELECT salary ,RANK_SALARY
from ( SELECT  DENSE_RANK() OVER (ORDER BY SALARY DESC) RANK_SALARY , Salary FROM Employees ) 
as tbl
WHERE RANK_SALARY = 4