CREATE TRIGGER MY_FIRST_TGR
ON HumanResources.Shift
FOR INSERT 
AS
	DECLARE @MY_VAR DATETIME
	SELECT @MY_VAR = MODIFIEDDATE FROM inserted 
	IF(@MY_VAR != GETDATE())
	BEGIN
		PRINT 'MODIFIED DATE SHOUDE BE THE CURRENT DATE HENCE , CANNOT INSERT'
		ROLLBACK TRANSACTION
	END


SELECT * FROM HumanResources.Shift
INSERT INTO HumanResources.Shift (4, 'Day' ,12 ,8 , '2008-04-30')