CREATE TABLE STUDENT (
	NAME NVARCHAR(20),
	ROLL_NO INT,
	MARKS INT
)
-- CLUSTERED INDEX

CLUSTERED INDEX IX_STU ON STUDENT (ROLL_NO) -- IT SHOUD PRIMARY KEY 

-- NON CLUSTERED INDEX
CREATE INDEX NIX_STU ON STUDENT (ROLL_NO) -- IT IS USE TO MAKE UNIQUE KEY 


SELECT * FROM STUDENT WHERE ROLL_NO = 1245

