BEGIN TRANSACTION SEC_TRAN
BEGIN TRY 
	UPDATE Student
	SET TotalFees = 5000
	WHERE StudentID = 2
	COMMIT TRANSACTION SEC_TRAN

	SELECT 'Transaction executed'
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION SEC_TRAN
	SELECT 'Transaction rollbacked'
END CATCH 

