SET TRANSACTION ISOLATION LEVEL
READ COMMITTED
BEGIN TRAN THIRD_TRAN
	BEGIN TRY 
	UPDATE Course
	SET CourseName = 'JAVA'
	WHERE CourseID  = 4

	COMMIT TRAN THIRD_TRAN
	PRINT 'TRANSACTION EXECUTED'
	END TRY

	BEGIN CATCH
		ROLLBACK TRAN THIRD_TRAN
		PRINT 'Transaction rollbacked'
	END CATCH
