

CREATE FUNCTION FUN_SECOND (@MONTH_ERN INT)
RETURNS INT
AS
BEGIN
    DECLARE @PT INT
    SELECT @PT=CASE
        WHEN (@MONTH_ERN < 6000 ) THEN 0
        WHEN (@MONTH_ERN > 6000 AND  @MONTH_ERN < 9000) THEN 80
        WHEN (@MONTH_ERN > 9000 AND    @MONTH_ERN < 12000) THEN 150
        WHEN (@MONTH_ERN > 12000 )THEN 200
        ELSE 0
    END
    RETURN @PT
END

DECLARE @ANS INT
SET @ANS  = dbo.FUN_SECOND(15000)
PRINT @ANS

