ALTER DATABASE AdventureWorks2012 SET ALLOW_SNAPSHOT_ISOLATION ON ALTER DATABASE AdventureWorks2012 SET READ_COMMITTED_SNAPSHOT ON

USE Adventureworks2012

--ISOLATION LEVELS PRACTICE
BEGIN TRANSACTION Tr

UPDATE HumanResources.Employee SET JobTitle='abc2'
	WHERE BusinessEntityID=3

PRINT 'TRANSACTION EXECUTED'
COMMIT TRANSACTION Tr

--
BEGIN TRANSACTION Tr

UPDATE HumanResources.Employee SET JobTitle='abc4'
	WHERE BusinessEntityID=4

PRINT 'TRANSACTION EXECUTED'
COMMIT TRANSACTION Tr

ROLLBACK TRANSACTION Tr

SELECT * FROM HumanResources.Employee WHERE JobTitle='abc4'

