CREATE TABLE Buses(
	BusNo VARCHAR(30) PRIMARY KEY NOT NULL,
	BusName VARCHAR(40) NOT NULL,
	Origin VARCHAR(50) NOT NULL,
	Destination VARCHAR(50) NOT NULL,
	ViaCities VARCHAR(MAX) NOT NULL,
	Fare MONEY NOT NULL,
	DepartureTime TIME NOT NULL,
	ArrivalTime TIME NOT NULL,
	RouteType VARCHAR(MAX) NOT NULL,
	BusType VARCHAR(70) NOT NULL
)

CREATE TABLE Agents(
	AgentID VARCHAR(30) PRIMARY KEY NOT NULL,
	Name VARCHAR(MAX) NOT NULL,
	Address VARCHAR(MAX) NOT NULL,
	PhoneNo INT NOT NULL,
	MobileNo INT NOT NULL,
	Email VARCHAR(50) NOT NULL,
	Profession VARCHAR(30) NOT NULL,
	AgencyAdd VARCHAR(MAX) NOT NULL,
	DepotName VARCHAR(60) NOT NULL,
	Aadhar INT NOT NULL,
	PAN VARCHAR(50) NOT NULL,
	BankName VARCHAR(50) NOT NULL,
	IFSC VARCHAR(50) NOT NULL,
	AccountNo VARCHAR(50) NOT NULL
)

CREATE TABLE CommuterPasses(
	ApplicationNo VARCHAR(20) NOT NULL,
	EntryDate DATE NOT NULL,
	PassType VARCHAR(20) NOT NULL,
	PasssangerType VARCHAR(40) NOT NULL,
	CommuterName VARCHAR(MAX) NOT NULL,
	Catagory VARCHAR(50) NOT NULL,
	MobileNo DECIMAL NOT NULL,
	Address VARCHAR(MAX) NOT NULL,
	Age INT NOT NULL,
	Email VARCHAR(60) NOT NULL,
	DOB DATE NOT NULL,
	Occupation VARCHAR(30) NOT NULL,
	Gender VARCHAR(20) NOT NULL,
	Education VARCHAR(20) NOT NULL,

)

CREATE TABLE Wallet(
	

)

CREATE TABLE Enquires(
	DivisionID INT NOT NULL PRIMARY KEY,
	DivisionName VARCHAR(50) NOT NULL
)

CREATE TABLE Divisions(
	DivisionID INT CONSTRAINT fkDivisionID FOREIGN KEY REFERENCES dbo.Enquires(DivisionID),
	BusStand VARCHAR(MAX) NOT NULL,
	EnquiryNo INT NOT NULL
)