// var date = new Date();
// console.log(date);
// date = new Date("2019-01-16");
// console.log(date);
// var date = new Date(2020, 12, 15, 2,15,58);
// console.log(date);
// console.log(date.getDate());
// console.log(date.getDay());
// date.setDate(1);
// console.log(date);
var date = new Date(2020, 0, 12, 15, 23, 42, 11);
console.log(date);
console.log("Year = " + date.getFullYear());
console.log("Date = " + date.getDate());
console.log("Month = " + date.getMonth());
console.log("Day = " + date.getDay());
console.log("Hours = " + date.getHours());
console.log("Minutes = " + date.getMinutes());
console.log("Seconds = " + date.getSeconds());
date.setDate(13);
date.setMonth(13);
date.setFullYear(2013);
date.setHours(13);
date.setMinutes(13);
date.setSeconds(13);
console.log("Year = " + date.getFullYear());
console.log("Date = " + date.getDate());
console.log("Month = " + date.getMonth());
console.log("Day = " + date.getDay());
console.log("Hours = " + date.getHours());
console.log("Minutes = " + date.getMinutes());
console.log("Seconds = " + date.getSeconds());
