BEGIN TRAN BANK_TRAN
DECLARE @DEBITED_AMOUNT MONEY

BEGIN TRY
	UPDATE Account
	SET TOTALAMOUNT = TOTALAMOUNT - @DEBITED_AMOUNT
	WHERE Ac_No = 1256132165

	UPDATE Account
	SET TOTALAMOUNT = TOTALAMOUNT + @DEBITED_AMOUNT
	WHERE Ac_No = 484613216

	COMMIT TRAN BANK_TRAN

	PRINT 'transction of your money is successful'

END TRY
BEGIN CATCH
	ROLLBACK TRAN BANK_TRAN
	PRINT 'transaction of your money is unsuccessful'
END CATCH



SELECT * FROM ACCOUNT
