const categoryData = [
    {
        _id: "60b0911907fbfa2d7c499716",
        CategoryName: "mobiles",
    },
    {
        _id: "60b0916807fbfa2d7c499718",
        CategoryName: "fashion",
    },
    {
        _id: "60b0915607fbfa2d7c499717",
        CategoryName: "electronics",
    },
];
const mobiledata = [
    {
        ProductName: "Vivo V20 Pro 8 GB 128 GB Midnight Jazz",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 29990,
        Qty: 50,
        image: "m1-1.webp",
        Rating: 3.7,
        featured: "false",
        Spec: [
            "16.36 cm (6.44 inch) Full HD+ Display",
            "8 GB RAM | 128 GB ROM",
            "Dual SIM",
            "4000 mAH Battery",
            "64MP + 8MP + 2MP | 44MP + 8MP Front Camera",
        ],
        moreInfo: ["m1-1.webp", "m1-2.webp", "m1-3.webp"],
    },
    {
        ProductName: "Redmi Note 9 Pro 4GB 64GB Interstellar Black",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 13577,
        Qty: 50,
        image: "m2-1.webp",
        Rating: 3.8,
        featured: "true",
        Spec: [
            "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB",
            "16.94 cm (6.67 inch) Full HD+ Display",
            "48MP + 8MP + 5MP + 2MP | 16MP Front Camera",
            "5020 mAh Battery",
            "Qualcomm Snapdragon 720G Processor",
        ],
        moreInfo: ["m2-1.webp", "m2-2.webp", "m2-3.webp"],
    },
    {
        ProductName: "OPPO F17 Pro 8GB 128GB Magic Blue",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 19990,
        Qty: 50,
        image: "m3-1.webp",
        Rating: 4.3,
        featured: "true",
        Spec: [
            "Display:-16.33 cm (6.43 inch)",
            "Memory:- RAM 8 GB, ROM 128, Expandable Memory 256 GB",
            "Camera:- Primary Camera 48 MP + 8 MP + 2 MP + 2 MP, Secondary Camera 16 MP+2 MP",
        ],
        moreInfo: ["m3-1.webp", "m3-2.webp", "m3-3.webp"],
    },
    {
        ProductName: "Realme Narzo 20 4 GB 64 GB Victory Blue",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 11725,
        Qty: 50,
        image: "m4-1.webp",
        Rating: 3.5,
        featured: "true",
        Spec: [
            "Display Size: 16.56 cm (6.52 inch)",
            "4 GB RAM | 64 GB ROM",
            "Resolution: HD Plus (1600 x 720 Pixels)",
            "Battery Capacity: 6000 mAh",
        ],
        moreInfo: ["m4-1.webp", "m4-2.webp", "m4-3.webp"],
    },
    {
        ProductName: "Realme C12 3 GB 32 GB Power Silver",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 9299,
        Qty: 50,
        image: "m5-1.webp",
        Rating: 4.1,
        featured: "true",
        Spec: [
            "Memory:- 3 GB RAM, 32 GB ROM, Expandable Upto 256 GB",
            "Display:- 16.56 cm (6.52 inch) HD+ Display",
            "Camera:- Camera:- 13 MP + 2 MP + 2 MP, 5 MP Front Camera",
            "6000 mAh Lithium-ion Battery",
        ],
        moreInfo: ["m5-1.webp", "m5-2.webp", "m5-3.webp"],
    },
    {
        ProductName: "Apple iPhone 12 Mini 64 GB Black",
        ProductCategory: "60b0911907fbfa2d7c499716",
        ProductType: "mobiles",
        ProductPrice: 69900,
        Qty: 50,
        image: "m6-1.webp",
        Rating: 5,
        featured: "true",
        Spec: [
            "64 GB ROM",
            "13.72 cm (5.4 inch) Super Retina XDR Display",
            "12MP + 12MP | 12MP Front Camera",
            "All Screen OLED Display",
        ],
        moreInfo: ["m6-1.webp", "m6-2.webp", "m6-3.webp"],
    },
];
const fashionData = [
    {
        ProductName:
            "BLISSTONE Men Mustard & Maroon Slim fit Cotton Blend Round neck T-Shirt - Pack Of 2",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 499,
        Qty: 20,
        image: "f1-1.webp",
        Rating: 4,
        featured: "true",
        Spec: ["S"],
        moreInfo: ["f1-1.webp", "f1-2.webp", "f1-3.webp"],
    },
    {
        ProductName: "Puma 19 FH Rubber Cricket Shoes For Men",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 5499,
        Qty: 30,
        image: "f2-1.webp",
        Rating: 3.7,
        featured: "true",
        Spec: ["7", "8", "9"],
        moreInfo: ["f2-1.webp", "f2-2.webp", "f2-3.webp"],
    },
    {
        ProductName: "Indian Beauty Women Blue & Pink Floral Regular Kurti",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 799,
        Qty: 30,
        image: "f3-1.webp",
        Rating: 3,
        featured: "true",
        Spec: ["S", "M", "L"],
        moreInfo: ["f3-1.webp", "f3-2.webp", "f3-3.webp"],
    },
    {
        ProductName: "Clothzy Women Solid Regular top - Red",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 469,
        Qty: 30,
        image: "f4-1.webp",
        Rating: 1,
        featured: "true",
        Spec: ["S", "M", "L"],
        moreInfo: ["f4-1.webp", "f4-2.webp", "f4-3.webp"],
    },
    {
        ProductName: "EPPE Men Green Hooded Hoodie",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 605,
        Qty: 30,
        image: "f5-1.webp",
        Rating: 2.5,
        featured: "false",
        Spec: ["S", "M", "L"],
        moreInfo: ["f5-1.webp", "f5-2.webp", "f5-3.webp"],
    },
    {
        ProductName: "Red Tape Men RSO0782A Walking Shoes ( Maroon )",
        ProductCategory: "60b0916807fbfa2d7c499718",
        ProductType: "fashion",
        ProductPrice: 1600,
        Qty: 30,
        image: "f6-1.webp",
        Rating: 4.5,
        featured: "false",
        Spec: ["7", "8", "9"],
        moreInfo: ["f6-1.webp", "f6-2.webp", "f6-3.webp"],
    },
];

const electronisData = [
    {
        ProductName:
            "boAt bassheads 100 BassHeads 100 In-Ear Wired Headphone ( Black )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 379,
        Qty: 30,
        image: "e1-1.webp",
        Rating: 4.1,
        featured: "true",
        Spec: [
            "Superior coated wired earphones are a definite fashion statement",
            "Powerful 10mm dynamic drivers for Super Extra Bass",
            "Features a HD microphone to make crystal clear calls",
            "Fits you perfectly with comfort and offers optimum length",
        ],
        moreInfo: ["e1-1.webp", "e1-2.webp", "e1-3.webp"],
    },
    {
        ProductName: "boAt Rockerz 235v2 In-Ear Bluetooth Headset ( Black )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 999,
        Qty: 30,
        image: "e2-1.webp",
        Rating: 4.1,
        featured: "true",
        Spec: ["Features a HD microphone to make crystal clear calls"],
        moreInfo: ["e2-1.webp", "e2-2.webp", "e2-3.webp"],
    },
    {
        ProductName:
            "Apple Airpods Pro True Wireless Bluetooth Headset ( White )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 21399,
        Qty: 30,
        image: "e3-1.webp",
        Rating: 4.3,
        featured: "true",
        Spec: [
            "Active Noise Cancellation",
            "Adaptive Equaliser Vent system for pressure equalisation",
            "Apple driver Custom high dynamic range amplifier",
            "Transparency mode",
        ],
        moreInfo: ["e3-1.webp", "e3-2.webp", "e3-3.webp"],
    },
    {
        ProductName: "Zebronics Zeb - Bro In-Ear Wired Headphone ( Black )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 222,
        Qty: 30,
        image: "e4-1.webp",
        Rating: 3.8,
        featured: "true",
        Spec: [
            "The earphone comes with a snug fit providing utmost comfort while wearing them regularly.",
            "Impedance 16 ?",
            "Frequency response 20Hz-20kHz",
        ],
        moreInfo: ["e4-1.webp", "e4-2.webp", "e4-3.webp"],
    },
    {
        ProductName: "BTK Trade i7s-TWS In-Ear Bluetooth Headset ( White )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 375,
        Qty: 0,
        image: "e5-1.webp",
        Rating: 3.5,
        featured: "false",
        Spec: [
            "Small & compact. Easy to carry in your pocket.",
            "2-3 hours of music play time/talk time.",
            "True wireless connectivity.",
        ],
        moreInfo: ["e5-1.webp", "e5-2.webp", "e5-3.webp"],
    },
    {
        ProductName: "realme Buds 2 In-Ear Wired Headphone ( Black )",
        ProductCategory: "60b0915607fbfa2d7c499717",
        ProductType: "electronics",
        ProductPrice: 599,
        Qty: 30,
        image: "e6-1.webp",
        Rating: 4.2,
        featured: "false",
        Spec: [
            "Three tactile buttons and a mic, so you can control your music and videos.",
            "Built-in magnets and a cable strap designed to provide the ultimate solution for neatly storing your earphones.",
            "The matte, streamlined design looks elegant and attractive.",
        ],
        moreInfo: ["e6-1.webp", "e6-2.webp", "e6-3.webp"],
    },
];
