export interface BookedHotelUserData
{
  hotelMobileNumber:number,
  hotelEmail:string,
  amount:number,
  tax: number,
  totelPrice:number,
  hotelName:string,
  hotelCity:string,
  hotelState:string,
  hotelAddress:string,
  pinNumber:number,
  rating:string,
  startingTime:string,
  closingTime:string,
  noOfRoomAvailable:number,
  imgPath1:string,
  imgPath2:string,
  imgPath3:string,
  imgPath4:string,
  userId: number,
  userReferenceNumumbar:string,
  userFirstName:string,
  userMiddleName:string,
  userLastName:string,
  userEmail:string,
  userContectNumber:number,
  numberOfGuest:number,
  costId: number,
  hotelId: number,
  contectId:number
}