DECLARE @VAR1 INT 
WHILE (SELECT AVG(ListPrice) FROM Production.Product) < 300
BEGIN
	PRINT 'ABEY SALLE'
 UPDATE Production.Product
	SET ListPrice = ListPrice *2;
	SELECT @VAR1 = AVG(LISTPRICE) FROM Production.Product
	PRINT @VAR1
	   IF (SELECT @VAR1  FROM PRODUCTION.PRODUCT )> 500
		BREAK
	   ELSE
	    CONTINUE
	END

	PRINT 'TOO MUCH FOR THE MARKET TO BEAR'
	GO