--Day 6 Assignmenet on Employee Table

-- 1

SELECT * FROM Employee 
WHERE EMPLOYEE_ID IN (SELECT EMPLOYEE_REF_ID FROM Incentive)

--2

SELECT * FROM Employee
WHERE SALARY > (SELECT SALARY FROM Employee WHERE FIRST_NAME = 'ROY')

--3

CREATE VIEW Employee_Inc
AS 
SELECT E.FIRST_NAME , E.LAST_NAME , E.SALARY , JOINING_DATE , I.INCENTIVE_DATE , I.INCENTIVE_AMOUNT FROM Employee AS E
JOIN Incentive AS I 
ON E.EMPLOYEE_ID = I.EMPLOYEE_REF_ID

-- 4

CREATE VIEW High_Inc_Emp
AS
SELECT E.FIRST_NAME , I.INCENTIVE_AMOUNT FROM Employee AS E
JOIN Incentive AS I
ON E.EMPLOYEE_ID = I.EMPLOYEE_REF_ID
WHERE I.INCENTIVE_AMOUNT > 3000





