const mongoose = require('mongoose');

const Schema = mongoose.Schema;

const EmpSchema = new Schema({
    Id: Number,
    Address:{
        line1: String,
        line2: String,
        line3: String
    },
    citizenshipID: Number,
    CitizenshipLegislationCode: String,
    CitizenshipStatus: String,
    CitizenshipToDate: Date,
    City: String,
    CorrespondenceLanguage: String,
    Country: String,
    CreationDate: Date,
    DateOfBirth: Date,
    directReports: Array,
    DisplayName: String,
    DriversLicenseExpirationDate: Date,
    DriversLicenseId: Number,
    DriversLicenseIssuingCountry: String,
    EffectiveStartDate: Date,
    FirstName: String,
    Gender: String,
    HireDate: Date,
    HomeFaxAreaCode: String,
    HomeFaxCountryCode: String,
    HomeFaxExtension: String,
    HomeFaxLegislationCode: String,
    HomeFaxNumber: String,
    LastName: String,
    LastUpdateDate: Date,
    LicenseNumber: String,
    links: Array,
    MaritalStatus: String,
    MiddleName: String,
    NameSuffix: String,
    NationalId: Number,
    NationalIdCountry: Number,
    Assignments:[
        {
            ActionCode: String,
            ActionReasonCode: String,
            ActualTerminationDate: Date,
            AssignmentCategory: String,
            AssignmentDFF: Array,
            AssignmentExtraInformation: Array,
            AssignmentId: Number,
            AssignmentName: String,
            AssignmentNumber: String,
            AssignmentProjectedEndDate: Date,
            AssignmentStatus: String,
            AssignmentStatusTypeId: Number,
            BusinessUnitId: Number,
            CreationDate: Date,
            DefaultExpenseAccount: String,
            DepartmentId: Number,
            EffectiveEndDate: Date,
            EffectiveStartDate: Date,
            Empreps: Array,
            EndTime: String,
            Frequency: String,
            FullPartTime: String,
            GradeId: Number,
            GradeLadderId: Number,
            JobId: Number,
            LastUpdateDate: Date,
            LegalEntityId: Number,
            links: Array,
            LocationId: Number,
            ManagerAssignmentId: Number,
            ManagerId: Number,
        }]
});

module.exports = mongoose.model('EmpData',EmpSchema);